info:
  contact: {}
paths:
  /login:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"","data":""}'
          schema:
            type: string
      summary: 用户登录
  /problem-detail:
    get:
      parameters:
      - description: problem_identity
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"","data":""}'
          schema:
            type: string
      summary: 问题详情
  /problem-list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: category_identity
        in: query
        name: category_identity
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"","data":""}'
          schema:
            type: string
      summary: 问题列表
  /rank-list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: '{"code":"200", "msg":"","data":""}'
          schema:
            type: string
      summary: 用户排行榜
  /register:
    post:
      parameters:
      - description: mail
        in: formData
        name: mail
        required: true
        type: string
      - description: code
        in: formData
        name: code
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      - description: phone
        in: formData
        name: phone
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"","data":""}'
          schema:
            type: string
      summary: 用户注册
  /send-code:
    post:
      parameters:
      - description: email
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"","data":""}'
          schema:
            type: string
      summary: 发送验证码
  /submit-list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: problem_identity
        in: query
        name: problem_identity
        type: string
      - description: user_identity
        in: query
        name: user_identity
        type: string
      - description: status
        in: query
        name: status
        type: integer
      responses:
        "200":
          description: '{"code":"200", "msg":"","data":""}'
          schema:
            type: string
      summary: 提交列表
  /user-detail:
    get:
      parameters:
      - description: user_identity
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"","data":""}'
          schema:
            type: string
      summary: 用户详情
swagger: "2.0"
